# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f988393c83dea504db9d3ec21ab802cec51686fe32a6b914092b09d8ffadd21224df09e2292196211a8dd8ffcc3337fb6c2b0dea0668b0cc88159365b4ca7669

test:
  secret_key_base: 25fba027ad20b9db677beab8ca8f763e1e62ca55fede3a7d17722d1139ee7865b9d953ef5302d5ff2624f6abfd5e3ed2e6c7f3070a21225b6e05faabc1519d92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
